### ISSUE TITLE
DB error if option "save for restore" is active

### ISSUE THREAD

**Issue by cfoellmann** [ATM-Consulting/dolibarr_module_history#14]
When I activate the option to "save deletions for restore" the history just gives a DB error in the list.

```
Fatal error: Uncaught Error: Call to a member function fetch_object() on boolean in /home/runcloud/webapps/dolibarr-testing/htdocs/core/db/mysqli.class.php:304 
Stack trace: 
#0 /home/runcloud/webapps/dolibarr-testing/htdocs/debugbar/class/TraceableDB.php(682): DoliDBMysqli->fetch_object(false) 
#1 /home/runcloud/webapps/dolibarr-testing/htdocs/custom/history/class/history.class.php(123): TraceableDB->fetch_object(false) 
#2 /home/runcloud/webapps/dolibarr-testing/htdocs/custom/history/history.php(135): DeepHistory->show_whatChanged(Object(TraceableDB)) 
#3 {main} thrown in /home/runcloud/webapps/dolibarr-testing/htdocs/core/db/mysqli.class.php on line 304
```

**Comment by cfoellmann** [comment]
@atm-john
I looked at the code and it seems that the tables for saving the deleted elements are not being created.
Is this not a feature that should be not-broken?

**Comment by cfoellmann** [comment]
these things I identified so far:

ECMFILES have some issues:
- DB table is `ecm_files` (not ecmfiles)
- class files and module folder are not named the same -> issue


- `function show_whatChanged()` has issues with db table names that diverge from class/element name
- function makeCopy()` has also issues with the db table names

maybe mapping missformed element names should be externalized from the functions
